src/Entity/Sports.php
<?php

namespace App\Entity;

use App\Repository\SportsRepository;
use Symfony\Component\Validator\Constraints as Assert;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=SportsRepository::class)
 */
class Sports
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @Assert\NotBlank
     * @Assert\Length(
     *      min = 2,
     *      max = 255,
     *      minMessage = "Le nom du sport est trop court, vous devez mettre un nom plus long.",
     *      maxMessage = "Votre nom de sport est trop long, vous devez raccourcir le nom."
     * )
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @Assert\NotBlank
     * @ORM\Column(type="text")
     *  * @Assert\Length(
     *      min = 10,  
     *      minMessage = "Votre description doit être plus longue.",     
     * )
     */
    private $description;

    /** 
     * @ORM\OneToMany(targetEntity=Pratiques::class, mappedBy="sportsData", orphanRemoval=true)
     */
    private $pratiqueSportive;

    /**
     * @ORM\Column(type="boolean")
     */
    private $is_verified;

    /**
     * @ORM\ManyToOne(targetEntity=Users::class, inversedBy="sportsCreate", cascade={"persist"})
     * @ORM\JoinColumn(nullable=true)
     */
    private $userSportif;

    public function __toString() {

    return $this->name;
    
    }

    public function __construct()
    {
        $this->pratiqueSportive = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    /**
     * @return Collection|Pratiques[]
     */
    public function getPratiqueSportive(): Collection
    {
        return $this->pratiqueSportive;
    }

    public function addPratiqueSportive(Pratiques $pratiqueSportive): self
    {
        if (!$this->pratiqueSportive->contains($pratiqueSportive)) {
            $this->pratiqueSportive[] = $pratiqueSportive;
            $pratiqueSportive->setSportsData($this);
        }

        return $this;
    }

    public function removePratiqueSportive(Pratiques $pratiqueSportive): self
    {
        if ($this->pratiqueSportive->removeElement($pratiqueSportive)) {
            // set the owning side to null (unless already changed)
            if ($pratiqueSportive->getSportsData() === $this) {
                $pratiqueSportive->setSportsData(null);
            }
        }

        return $this;
    }

    public function getIsVerified(): ?bool
    {
        return $this->is_verified;
    }

    public function setIsVerified(bool $is_verified): self
    {
        $this->is_verified = $is_verified;

        return $this;
    }

    public function getUserSportif(): ?Users
    {
        return $this->userSportif;
    }

    public function setUserSportif(?Users $userSportif): self
    {
        $this->userSportif = $userSportif;

        return $this;
    }    
}

src/Controller/Admin/AdminSportsController.php
<?php

namespace App\Controller\Admin;

use App\Entity\Sports;
use App\Form\SportsType;
use App\Repository\SportsRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

/**
 * @Route("/admin/sports") 
 * Require ROLE_ADMIN for *every* controller method in this class.
 * @IsGranted("ROLE_ADMIN")
 * 
 */
class AdminSportsController extends AbstractController
{
    /**
     * @Route("/", name="admin_sports_index", methods={"GET"})
     * @IsGranted("ROLE_ADMIN")
     */
    public function index(SportsRepository $sportsRepository): Response
    {
        return $this->render('admin_sports/index.html.twig', [
            'sports' => $sportsRepository->findBy(['is_verified' => false]),
        ]);
    }
    
    /**
     * @Route("/{id}", name="admin_sports_show", methods={"GET"})
     * @IsGranted("ROLE_ADMIN")
     */
    public function show(Sports $sport): Response
    {
        return $this->render('admin_sports/show.html.twig', [
            'sport' => $sport,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="admin_sports_edit", methods={"GET","POST"})
     * @IsGranted("ROLE_ADMIN")
     */
    public function edit(Request $request, Sports $sport): Response
    {
        $form = $this->createForm(SportsType::class, $sport);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('admin_sports_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('admin_sports/edit.html.twig', [
            'sport' => $sport,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="admin_sports_delete", methods={"POST"})
     * @IsGranted("ROLE_ADMIN")
     */
    public function delete(Request $request, Sports $sport): Response
    {
        if ($this->isCsrfTokenValid('delete'.$sport->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($sport);
            $entityManager->flush();
        }

        return $this->redirectToRoute('admin_sports_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/admin_sports/_delete_form.html.twig
<form method="post" action="{{ path('admin_sports_delete', {'id': sport.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ sport.id) }}">
    <button class="btn btn-danger">Supprimer</button>
</form>

templates/admin_sports/_form.html.twig
{{ form_start(form) }}
   
        <div class="form-group mb-2">
            <label for="name" class="col-sm-2 col-form-label">Nom du sport :</label>
                {{ form_widget(form.name, {'attr': {"class" : "form-control form-control-sm"}}) }}
                {{ form_errors(form.name) }}
        </div>
        <div class="form-group mb-2">
            <label for="description">Description :</label>
            {{form_widget(form.description, {'attr': {"class" : "form-control form-control-sm"}}) }}
            {{ form_errors(form.description) }}
        </div>
        <div>
            <label class="form-check-label" for="is_verified">Valider </label>
            {{form_widget(form.is_verified, {'attr': {"class" : "form-check-input"}}) }}
            {{ form_errors(form.is_verified) }}
        </div>        
        <div class="text-center">        
            <button class="btn btn-success m-1">{{ button_label|default('Confirmer définitivement') }}</button>
        </div>
{{ form_end(form) }}

templates/admin_sports/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Valider un Sport{% endblock %}

{% block stylesheets %}
<link href="{{ asset('./assets/css/admin/admin.css') }}" type="text/css" rel="stylesheet" />
{% endblock %}

{% block body %}
    <h1 class="text-center">Valider le sport</h1>
<div class="container">

        <div class="row blocForm">
            {{ include('admin_sports/_form.html.twig', {'button_label': 'Confirmer définitivement'}) }}
        </div>
</div>
    <div class="blocBtn">
        <div><a class="btn btn-dark m-1" href="{{ path('admin_sports_index') }}">Retour</a></div>

        <div>{{ include('admin_sports/_delete_form.html.twig') }}</div>
    </div>
    
{% endblock %}

templates/admin_sports/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Sports index{% endblock %}

{% block stylesheets %}
<link href="{{ asset('./assets/css/admin/admin.css') }}" type="text/css" rel="stylesheet" />
{% endblock %}

{% block body %}
{% include "partials/navAdmin.html.twig" %}
    <h1 class="text-center">Sports à valider</h1>

<div class="table-responsive">

    <table class="table">
        <thead>
            <tr class="table-primary">                
                <th>Nom</th>
                <th>Description</th>
                <th>Valider</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
        {% for sport in sports %}
            <tr>                
                <td>{{ sport.name }}</td>
                <td>{{ sport.description }}</td>
                <td>{{ sport.isVerified ? 'Yes' : 'No' }}</td>
                <td>
                    <a class="btn btn-primary m-1" href="{{ path('admin_sports_show', {'id': sport.id}) }}">Détails</a>
                    <a class="btn btn-warning m-1" href="{{ path('admin_sports_edit', {'id': sport.id}) }}">Modifier et valider</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">Aucun résultat</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>   

<div class="eltRetrour">
    <div class="return">
        <a id="retour" href="{{ path("admin_index") }}">Tableau de bord</a>
    </div>
</div>   
{% endblock %}

templates/admin_sports/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Sports{% endblock %}

{% block stylesheets %}
<link href="{{ asset('./assets/css/admin/admin.css') }}" type="text/css" rel="stylesheet" />
{% endblock %}

{% block body %}
    <h1 class="text-center">Le sport à valider</h1>
<div class="table-responsive">
    <table class="table">
        <tbody>            
            <tr>
                <th class="table-primary">Nom</th>
                <td class="table-warning">{{ sport.name }}</td>
            </tr>
            <tr>
                <th class="table-primary">Description</th>
                <td class="table-warning">{{ sport.description }}</td>
            </tr>
            <tr>
                <th class="table-primary">Vérifier</th>
                <td class="table-warning">{{ sport.isVerified ? 'Yes' : 'No' }}</td>
            </tr>
        </tbody>
    </table>
</div>
    <div class="blocBtn">
        <div class="m-1"><a class="btn btn-dark" href="{{ path('admin_sports_index') }}">Retour</a></div>

        <div class="m-1"><a class="btn btn-warning" href="{{ path('admin_sports_edit', {'id': sport.id}) }}">Modifier ou/et valider</a></div>

        <div class="m-1">{{ include('admin_sports/_delete_form.html.twig') }}
        </div>
    </div>
{% endblock %}